# Mod properties
mod_id = camelnostrils
mod_name = Camel Nostrils
mod_description = Absurd, spouse-suggested nonsense, starting with a camel's nose.
mod_version = 1.0.0
maven_group = com.chimericdream.camelnostrils
archives_name = camelnostrils
enabled_platforms = fabric,neoforge

# Compatibility versions
minecraft_compat = 26.2
