modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/chimericdream/houdiniblock/issues"
license = "MIT"

[[mods]]
modId = "houdiniblock"
version = "${version}"
displayName = "Houdini Block"
authors = "chimericdream"
description = '''
A magical block that doesn't trigger block updates when broken!
'''
#logoFile = ""

[[dependencies.houdiniblock]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.houdiniblock]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.houdiniblock]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.houdiniblock]]
modId = "chimericlib"
type = "required"
versionRange = "[2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "META-INF/houdiniblock.neoforge.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"
