# Mod properties
mod_id = logallthethings
mod_name = Log All the Things!
mod_description = Water-logging behavior, but for lava, carpet, and glass panes too.
mod_version = 1.0.0-beta.0
maven_group = com.chimericdream.logallthethings
archives_name = logallthethings
enabled_platforms = fabric,neoforge

# Compatibility versions
minecraft_compat = 26.2
