modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/chimericdream/athenaeum-mod/issues"
license = "MIT"

[[mods]]
modId = "athenaeum"
version = "${version}"
displayName = "Athenaeum"
authors = "chimericdream"
description = '''
This mod adds a variety of custom written books and related content to the game.
'''
logoFile = "/assets/athenaeum/icon.png"

[[dependencies.athenaeum]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.athenaeum]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.athenaeum]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.athenaeum]]
modId = "chimericlib"
type = "required"
versionRange = "[2.2.0-beta.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.athenaeum]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.6.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "athenaeum.mixins.json"
