modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/chimericdream/hopper-extreme/issues"
license = "MIT"

[[mods]]
modId = "hopperxtreme"
version = "${version}"
displayName = "Hopper X-Treme"
authors = "chimericdream"
description = '''
Upgrade your hoppers!
'''
#logoFile = ""

[[dependencies.hopperxtreme]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hopperxtreme]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hopperxtreme]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "hopperxtreme.mixins.json"
