# Mod properties
mod_id = allhallowssteve
mod_name = All Hallows Steve
mod_description = Halloween-themed blocks, items, and pumpkin dyeing.
mod_version = 1.0.0
maven_group = com.chimericdream.allhallowssteve
archives_name = allhallowssteve
enabled_platforms = fabric,neoforge

# Compatibility versions
minecraft_compat = 26.2
