architectury {
    fabric()
}

loom {
    accessWidenerPath = project(":all-hallows-steve:common").loom.accessWidenerPath

    runs {
        datagen {
            inherit client
            name "Data Generation"
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.output-dir=${project(':all-hallows-steve:common').file("src/main/generated")}"
            vmArg "-Dfabric-api.datagen.modid=${mod_id}"
            runDir "build/datagen"
        }
    }
}

configurations {
    developmentFabric.extendsFrom common
}

dependencies {
    common(project(path: ':all-hallows-steve:common')) { transitive false }
    shadowBundle project(path: ':all-hallows-steve:common', configuration: 'transformProductionFabric')
}
