modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "pannotiacompanion"
version = "${version}"
displayName = "Pannotia Companion"
authors = "chimericdream"
description = '''
Companion mod for the World of Pannotia modpack
'''
#logoFile = ""

[[dependencies.pannotiacompanion]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pannotiacompanion]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pannotiacompanion]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.pannotiacompanion]]
modId = "chimericlib"
type = "required"
versionRange = "[2.2.0-beta.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.pannotiacompanion]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.6.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "pannotiacompanion.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"
