architectury {
    fabric()
}

loom {
    accessWidenerPath = project(":next-update-now:common").loom.accessWidenerPath
}

configurations {
    developmentFabric.extendsFrom common
}

dependencies {
    common(project(path: ':next-update-now:common')) { transitive false }
    shadowBundle project(path: ':next-update-now:common', configuration: 'transformProductionFabric')
}
