architectury {
    fabric()
}

loom {
    accessWidenerPath = project(":sneaky-tweaks:common").loom.accessWidenerPath
}

configurations {
    developmentFabric.extendsFrom common
}

dependencies {
    common(project(path: ':sneaky-tweaks:common')) { transitive false }
    shadowBundle project(path: ':sneaky-tweaks:common', configuration: 'transformProductionFabric')
}
