# Mod properties
mod_id = effectivegear
mod_name = Effective Gear
mod_description = Small quality-of-life tweaks and bonuses for player armor, weapons, and tools.
mod_version = 1.0.0
maven_group = com.chimericdream.effectivegear
archives_name = effectivegear
enabled_platforms = fabric,neoforge

# Compatibility versions
minecraft_compat = 26.2
chimericlib_compat = 6.4.0
