modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/chimericdream/cobblicious-mod/issues"
license = "MIT"

[[mods]]
modId = "cobblicious"
version = "${version}"
displayName = "Cobblicious"
authors = "chimericdream"
description = '''
This mod adds a variety of custom written books and related content to the game.
'''
logoFile = "/assets/cobblicious/icon.png"

[[dependencies.cobblicious]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblicious]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblicious]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "cobblicious.mixins.json"
