# Mod properties
mod_id = minekea
mod_name = Minekea
mod_description = Simple, functional, decorative blocks for all your building and storage needs (some assembly required)
mod_version = 9.0.0
maven_group = com.chimericdream.minekea
archives_name = minekea
enabled_platforms = fabric,neoforge
has_patchouli_guide = true

# Compatibility versions
chimericlib_compat = 5.0.0
minecraft_compat = 26.1.2
patchouli_compat = 1.21-87
