# Mod properties
mod_id = jdcrafte
mod_name = JD Crafte
mod_description = One-stop shop for all your farming and agricultural needs!
mod_version = 1.0.0-beta.0
maven_group = com.chimericdream.jdcrafte
archives_name = jdcrafte
enabled_platforms = fabric,neoforge
has_fabric_datagen = true

# Compatibility versions
minecraft_compat = 26.2
