# Mod properties
mod_id = betterportallinking
mod_name = Better Portal Linking
mod_description = Gives players more control over how their nether portals link between the Nether and Overworld.
mod_version = 1.0.0
maven_group = com.chimericdream.betterportallinking
archives_name = betterportallinking
enabled_platforms = fabric,neoforge

# Compatibility versions
minecraft_compat = 26.2
