modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/chimericdream/minecraft-mods/issues"
license = "MIT"

[[mods]]
modId = "beaconconduittweaks"
version = "${version}"
displayName = "beaconconduittweaks"
authors = "chimericdream"
description = '''
Some description here
'''
#logoFile = ""

[[dependencies.beaconconduittweaks]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beaconconduittweaks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beaconconduittweaks]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.beaconconduittweaks]]
modId = "chimericlib"
type = "required"
versionRange = "[2.2.0-beta.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.beaconconduittweaks]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.6.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "beaconconduittweaks.mixins.json"
