# Mod properties
mod_id = butwhatabout
mod_name = But What About...?
mod_description = When Mojang adds new blocks to the game, but leaves some out, this mod fills in the gaps.
mod_version = 1.0.0-beta.0
maven_group = com.chimericdream.butwhatabout
archives_name = but-what-about
enabled_platforms = fabric,neoforge
has_fabric_datagen = true

# Compatibility versions
minecraft_compat = 26.2
