import org.gradle.jvm.tasks.Jar

plugins {
    id 'com.gradleup.shadow'
}

architectury {
    neoForge()
}

loom {
    accessWidenerPath = project(":better-portal-linking:common").loom.accessWidenerPath

    neoForge {
        convertAccessWideners(tasks.named("shadowJar", Jar), "betterportallinking.accesswidener")
    }
}

configurations {
    developmentNeoForge.extendsFrom common
}

dependencies {
    common(project(path: ':better-portal-linking:common')) { transitive false }
    shadowBundle project(path: ':better-portal-linking:common', configuration: 'transformProductionNeoForge')
}
