# Mod properties
mod_id = pannotiacompanion
mod_name = Pannotia Companion
mod_description = Companion mod for the World of Pannotia modpack
mod_version = 1.0.0
maven_group = com.chimericdream.pannotiacompanion
archives_name = pannotiacompanion
enabled_platforms = fabric,neoforge

# Compatibility versions
minecraft_compat = 26.2
