architectury {
    fabric()
}

loom {
    accessWidenerPath = project(":opus:common").loom.accessWidenerPath
}

configurations {
    developmentFabric.extendsFrom common
}

dependencies {
    common(project(path: ':opus:common')) { transitive false }
    shadowBundle project(path: ':opus:common', configuration: 'transformProductionFabric')
}
