architectury {
    fabric()
}

loom {
    accessWidenerPath = project(":camel-nostrils:common").loom.accessWidenerPath
}

configurations {
    developmentFabric.extendsFrom common
}

dependencies {
    common(project(path: ':camel-nostrils:common')) { transitive false }
    shadowBundle project(path: ':camel-nostrils:common', configuration: 'transformProductionFabric')
}
