# Mod properties
mod_id = sneakytweaks
mod_name = Sneaky Tweaks
mod_description = Minor tweaks and enhancements around what happens when you sneak around
mod_version = 1.0.0
maven_group = com.chimericdream.sneakytweaks
archives_name = sneakytweaks
enabled_platforms = fabric,neoforge

# Compatibility versions
minecraft_compat = 26.2
