modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/chimericdream/banner-tweaks/issues"
license = "MIT"

[[mods]]
modId = "bannertweaks"
version = "${version}"
displayName = "Banner Tweaks"
authors = "chimericdream"
description = '''
A mod that provides some vanilla-friendly tweaks to banners.
'''
logoFile = "assets/bannertweaks/icon.png"

[[dependencies.bannertweaks]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bannertweaks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bannertweaks]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bannertweaks]]
modId = "chimericlib"
type = "required"
versionRange = "[2.2.0-beta.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bannertweaks]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.6.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "bannertweaks.mixins.json"

[[mixins]]
config = "bannertweaks-neoforge.mixins.json"
