# Mod properties
mod_id = toybox
mod_name = Toy Box
mod_description = Creeper-in-a-box, talking villager dolls, and other such toys and decorative items
mod_version = 1.0.0
maven_group = com.chimericdream.toybox
archives_name = toybox
enabled_platforms = fabric,neoforge

# Compatibility versions
minecraft_compat = 26.2
