modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/chimericdream/blacklight-mod/issues"
license = "MIT"

[[mods]]
modId = "blacklight"
version = "${version}"
displayName = "blacklight"
authors = "chimericdream"
description = '''
This mod adds a variety of custom written books and related content to the game.
'''
logoFile = "/assets/blacklight/icon.png"

[[dependencies.blacklight]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blacklight]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blacklight]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "blacklight.mixins.json"
