modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/chimericdream/chimericlib-mc/issues"
license = "MIT"

[[mods]]
modId = "chimericlib"
version = "${version}"
displayName = "chimericlib"
authors = "chimericdream"
description = '''
Shared library with common code for chimericdream's mods.
'''
#logoFile = ""

[[dependencies.chimericlib]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chimericlib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chimericlib]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "chimericlib.mixins.json"
