# Mod properties
mod_id = bettertargetdummies
mod_name = Better Target Dummies
mod_description = Craft a target dummy block that can take on the skin of any mob, so you can test how attacks and damage types perform against specific mobs and mob categories.
mod_version = 1.0.0
maven_group = com.chimericdream.bettertargetdummies
archives_name = bettertargetdummies
enabled_platforms = fabric,neoforge

# Compatibility versions
minecraft_compat = 26.2
