architectury {
    fabric()
}

loom {
    accessWidenerPath = project(":better-portal-linking:common").loom.accessWidenerPath
}

configurations {
    developmentFabric.extendsFrom common
}

dependencies {
    common(project(path: ':better-portal-linking:common')) { transitive false }
    shadowBundle project(path: ':better-portal-linking:common', configuration: 'transformProductionFabric')
}
