# Mod properties
mod_id = nextupdatenow
mod_name = Next Update Now
mod_description = Get content from the next update on the current version!
mod_version = 1.0.1
maven_group = com.chimericdream.nextupdatenow
archives_name = nextupdatenow
enabled_platforms = fabric,neoforge

# Compatibility versions
minecraft_compat = 26.2
