modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/chimericdream/minecraft-mods/issues"
license = "MIT"

[[mods]]
modId = "villagertweaks"
version = "${version}"
displayName = "villagertweaks"
authors = "chimericdream"
description = '''
Some description here
'''
#logoFile = ""

[[dependencies.villagertweaks]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.villagertweaks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.villagertweaks]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.villagertweaks]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.6.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "villagertweaks.mixins.json"
