# Mod properties
mod_id = stackitup
mod_name = StackItUp
mod_description = AllStackable, reborn for Fabric and NeoForge in the 26.x+ era.
mod_version = 1.0.0
maven_group = com.chimericdream.stackitup
archives_name = stackitup
enabled_platforms = fabric,neoforge

# Compatibility versions
minecraft_compat = 26.2
